### ISSUE TITLE
Work on R 3.1

### ISSUE THREAD

**Issue by hadley** [brodieG/fansi#45]
It would be great to have R 3.1 support, since otherwise it's hard for us to use within tidyverse/R-lib.

**Comment by brodieG** [comment]
I understand, @gaborcsardi requested as much.  Unfortunately, `R_nchar` was exposed between 3.1 and 3.2 in Rinternals.h, so I can't go back to 3.1 without a huge amount of work.

It might be possible to have a subset of the functionality that doesn't use width computations though, if that is helpful I'll consider it (although not right away as that will still be a bit of work with conditional compilation, etc.).

**Comment by gaborcsardi** [comment]
Could you call back to R's `nchar` on R 3.1?  This is of course much slower, but if you only do it once or a few times, then maybe it is possible?

**Comment by gaborcsardi** [comment]
Btw. you need `nchar(type = "width")`, right?

**Comment by brodieG** [comment]
That's right, although I'm pretty sure that was available as of 3.1.  I think using `nchar` will be difficult because right now the code is set up to process a stream of characters.  In order to use `nchar` without completely crushing performance I'll need to do a two pass process that identifies all the non-ASCII characters and computes their width with one `nchar` call, and then shim that back into the existing stream logic.  That is a bit of work and substantially increases the complexity of the code.

Of course, this is all doable, but I do wonder whether it is worth it.  How long are you planning on supporting 3.1?  3.2 is about to have its third birthday, and 3.5 release is around the corner.

Two other bad options include literally calling `nchar` for every non-ascii character, which will be terrible performance wise, or writing custom grapheme width calculations (or more likely, integrating some of Pat Perry's work).

**Comment by brodieG** [comment]
A third option is to have a "crippled" version of the package in 3.1 which supports:

* `substr` (but not width based)
* `strsplit`
* `nchar`/`nzchar`
* `sgr_to_html`

as those don't require width calculations.  The other functions could be made to work by assuming that every character is one wide.  The package would warn via a startup message about its crippled state.

**Comment by hadley** [comment]
Unless you have some support for 3.1 (even if it's partial), we can't depend on it in cli, because cli is (or will be) used by the majority of packages in the tidyverse. At some point in the future, we will consider upgrading our base version to 3.2, but I think that should be a deliberate choice.

A crippled version for 3.1 is fine, as long as it doesn't crash and passes R CMD check. I'm not sure a package startup message is even needed.

**Comment by brodieG** [comment]
Ok I can do that.

**Comment by gaborcsardi** [comment]
I think we can just turn off colors on R 3.1.x, in the tidyverse/r-lib packages.

**Comment by brodieG** [comment]
I think I'm mostly done with this (I'm just adding a stub R_nchar if R < 3.2).  I do need to build 3.1 for testing, if that turns out to be more difficult than anticipated I'll let you know.

**Comment by gaborcsardi** [comment]
```
docker pull rocker/r-ver:3.1
```
???

**Comment by brodieG** [comment]
[sheepishly]Yeah, I guess I don't actually need to test this with valgrind instrumentation, do I?[sheepishly]

**Comment by gaborcsardi** [comment]
Yeah, nobody tests R 3.1 with valgrind....

**Comment by hadley** [comment]
Yeah, we can turn off colours, but we can't conditionally import a package (i.e. the main thing we care about is the depends field and passing R CMD check on R 3.1)

**Comment by brodieG** [comment]
This (development branch) now builds, installs, and runs on R 3.1, though do note the test suite is skipped, and width calculations for wide display characters (or even zero width characters) do not work properly.

https://travis-ci.org/brodieG/fansi/jobs/361921785

Please confirm this meets your requirements.

Since "Days since last update: 3" I will need to wait a couple of weeks before I can resubmit to CRAN.

**Comment by gaborcsardi** [comment]
Thanks, great!
