### ISSUE TITLE
sgr_to_html() adds unneeded <span>

### ISSUE THREAD

**Issue by hadley** [brodieG/fansi#69]
``` r
x <- "<div>\033[31mx\033[39m y</div>"
fansi::sgr_to_html(x)
#> [1] "<div><span style='color: #BB0000;'>x</span><span> y</div></span>"
```

<sup>Created on 2021-04-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I think the result should be:

```R
#> [1] "<div><span style='color: #BB0000;'>x</span> y</div>"
```

?

**Comment by brodieG** [comment]
It's to simplify the string writing logic, since it's in C and a pain:

https://github.com/brodieG/fansi/blob/master/src/tohtml.c#L177

Also, there is some interaction with #59, apparently:

https://github.com/brodieG/fansi/blob/master/src/tohtml.c#L503

Obviously the example you provide is not nice, but are you really dealing with mixed SGR/HTML?  I can contemplate doing this cleaner, but there would have to be a compelling case to so since it's going to be annoying.  Obviously conceptually it's simple, but making sure I don't introduce any subtle bugs in the process will take some work.

**Comment by hadley** [comment]
It's not a big deal; I've worked around it from end by doing the SGR conversion earlier.

**Comment by brodieG** [comment]
Ok, so I probably won't do anything about it, but will keep it open for whenever I get around to the css class thing, as that would be a natural moment to tackle this as well.

**Comment by brodieG** [comment]
0.5.0 produces more efficient html.

Do note you probably should `html_esc` the input as even `>` or `<` will mess up the HTML.  I'm considering having that be the default, but I'm a bit worried I'll break code that manually escapes, so might not make that change.
